global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: book-app
    metrics_path: /api/metrics
    static_configs:
      - targets: ["app:3000"]

  - job_name: book-health
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ["http://app:3000/api/health", "http://app:3000/api/version"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: uptime-kuma
    static_configs:
      - targets: ["uptime-kuma:3001"]

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]
