ALTER TYPE "UserSecurityEventType" ADD VALUE IF NOT EXISTS 'CONTENT_ACCESS_TOKEN_INVALID';
ALTER TYPE "UserSecurityEventType" ADD VALUE IF NOT EXISTS 'CONTENT_ACCESS_REPLAY_AFTER_REVOCATION';
ALTER TYPE "UserSecurityEventType" ADD VALUE IF NOT EXISTS 'CONTENT_ACCESS_MULTIPLE_DEVICE_ANOMALY';
ALTER TYPE "UserSecurityEventType" ADD VALUE IF NOT EXISTS 'SUSPICIOUS_ACCOUNT_ACTIVITY';
